---

- name: add influxdb repo
  template:
    src: influxdb.repo
    dest: /etc/yum.repos.d/influxdb.repo
  become: true

- name: install telegraf
  yum:
    name: telegraf
    state: present
  become: true

- name: configure telegraf
  template:
    src: telegraf.conf
    dest: /etc/telegraf/telegraf.conf
  become: true

- name: allow telegraf to docker stats
  user:
    name: telegraf
    groups: docker
    append: yes
  become: true

- name: start telegraf service
  systemd:
    state: restarted
    name: telegraf
  become: true

- name: start telegraf service
  systemd:
    state: restarted
    name: shinyproxy
  become: true

- name: enable telegraf service
  systemd:
    enabled: yes
    name: telegraf
    masked: no
  become: true

...
