- name: install nginx service
  yum:
    name: 
    - nginx
    - openssl
    state: present
  become: true

- name: create nginx config file
  template:
    src: shinyproxy.conf.j2
    dest: "/etc/nginx/sites-available/{{ shinyproxy.domain_name }}.conf"
  become: true

- name: restart nginx service, also issue daemon-reload to pick up config changes
  systemd:
    state: restarted
    daemon_reload: yes
    name: nginx
  become: true

- name: enable nginx service on boot
  systemd:
    enabled: yes
    name: ngixn
    masked: no
  become: true

- name: Generate a Self Signed OpenSSL certificate
  openssl_certificate:
    path: /etc/ssl/crt/ansible.com.crt
    privatekey_path: /etc/ssl/private/ansible.com.pem
    csr_path: /etc/ssl/csr/ansible.com.csr
    provider: selfsigned
