- name: install nginx service
  yum:
    name: 
    - nginx
    - openssl
    state: present
  become: true

- name: check if ssl private directory exists
  stat:
    path: /etc/ssl/private
    register: private_folder

- name: check if ssl certs directory exists
  stat:
    path: /etc/ssl/certs
    register: certs_folder

- name: create private directorie in etc ssl path
  file:
    path: /etc/ssl/private
    state: directory
    owner: root
    group: root
    mode: 0710
  become: true
  when: private_folder.stat.exists == false

- name: create certs directorie in etc ssl path
  file:
    path: /etc/ssl/certs
    state: directory
    owner: root
    group: root
    mode: 0750
  become: true
  when: certs_folder.stat.exists == false

- name: generate an OpenSSL private key.
  openssl_privatekey:
    path: /etc/ssl/private/{{ domain_name }}.key

- name: generate an OpenSSL CSR.
  openssl_csr:
    path: /etc/ssl/certs/{{ domain_name }}.csr
    privatekey_path: /etc/ssl/private/{{ domain_name }}.key
    common_name: "{{ domain_name }}"

- name: generate a Self Signed OpenSSL certificate
  openssl_certificate:
    path: /etc/ssl/certs/{{ domain_name }}.crt
    privatekey_path: /etc/ssl/private/{{ domain_name }}.key
    csr_path: /etc/ssl/certs/{{ domain_name }}.csr
    provider: selfsigned

- name: create nginx config file
  template:
    src: shinyproxy.conf.j2
    dest: "/etc/nginx/sites-available/{{ domain_name }}.conf"
  become: true

- name: restart nginx service, also issue daemon-reload to pick up config changes
  systemd:
    state: restarted
    daemon_reload: yes
    name: nginx
  become: true

- name: enable nginx service on boot
  systemd:
    enabled: yes
    name: ngixn
    masked: no
  become: true
