- name: install nginx service
  yum:
    name: 
    - nginx
    - openssl
    state: present
  become: true

- name: Generate an OpenSSL private key.
  openssl_privatekey:
    path: /etc/ssl/private/{{ shinyproxy.domain_name }}.key

- name: Generate an OpenSSL CSR.
  openssl_csr:
    path: /etc/ssl/certs/{{ shinyproxy.domain_name }}.csr
    privatekey_path: /etc/ssl/private/{{ shinyproxy.domain_name }}.key
    common_name: "{{ shinyproxy.domain_name }}"

- name: Generate a Self Signed OpenSSL certificate
  openssl_certificate:
    path: /etc/ssl/certs/{{ shinyproxy.domain_name }}.crt
    privatekey_path: /etc/ssl/private/{{ shinyproxy.domain_name }}.key
    csr_path: /etc/ssl/certs/{{ shinyproxy.domain_name }}.csr
    provider: selfsigned

- name: create nginx config file
  template:
    src: shinyproxy.conf.j2
    dest: "/etc/nginx/sites-available/{{ shinyproxy.domain_name }}.conf"
  become: true

- name: restart nginx service, also issue daemon-reload to pick up config changes
  systemd:
    state: restarted
    daemon_reload: yes
    name: nginx
  become: true

- name: enable nginx service on boot
  systemd:
    enabled: yes
    name: ngixn
    masked: no
  become: true
