---

- name: ShinyProxy installation
  gather_facts: false
  hosts: shinyservers
  roles:
    - { role: shinyproxy, tags: shinyproxy }
    - { role: monitoring, tags: monitoring }
    - { role: common, tags: common }

...
