proxy:
  title: Animated NYC metro traffic
  port: 8080
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  authentication: simple
  admin-groups: admins
  users:
  - name: jack
    password: password
    groups: admins
  - name: jeff
    password: password
  docker:
    cert-path: /home/none
    url: http://localhost:2375
    port-range-start: 20000
  specs:
    - id: nyc_metro_vis
      display-name: Animated NYC metro traffic
      container-cmd: ["R", "-e", "shiny::runApp('/root/NYC_Metro_Vis')"]
      container-image: shinyappsacr.azurecr.io/shinyapps/nycmetrovis

logging:
  file:
    shinyproxy.log
